{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-15701"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://launchpad.net/bugs/1877023",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://launchpad.net/bugs/1877023"
        },
        {
          "name": "https://usn.ubuntu.com/4449-1",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://usn.ubuntu.com/4449-1"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-08-07T14:13Z",
  "publishedDate": "2020-08-06T23:15Z"
}